-- This module serves as the root of the `FastMultiplication` library.
-- Import modules here that should be built as part of the library.
import FastMultiplication.ShorVerification.Implementation.Shared.Registers
import FastMultiplication.ShorVerification.Implementation.PhaseProduct.Proofs.Lowering.Workspace
import FastMultiplication.ShorVerification.Implementation.Shor.Proofs.Budgets
import FastMultiplication.ShorVerification.Implementation.Shor.Proofs.Setup
import FastMultiplication.ShorVerification.Implementation.Shor.Proofs.Readiness.Dynamic
import FastMultiplication.ShorVerification.Implementation.Shor.Proofs.Correctness
import FastMultiplication.ShorVerification.Implementation.Shor.Main
import FastMultiplication.ShorVerification.Implementation.PhaseProduct.Main
import FastMultiplication.ShorVerification.Implementation.QFT.Main
import FastMultiplication.ShorVerification.Implementation.ModularExponentiation.Main
import FastMultiplication.ShorVerification.Implementation.GateCount.QFT_GateCount
import FastMultiplication.ShorVerification.Implementation.GateCount.Shor_GateCount
import FastMultiplication.ShorVerification.Framework.Contract
import FastMultiplication.ShorVerification.Framework.Instantiation.QSemantics
import FastMultiplication.ShorVerification.Framework.Instantiation.RegEncoding
import FastMultiplication.ShorVerification.Framework.Instantiation.GateSemanticsCore
import FastMultiplication.ShorVerification.Framework.Instantiation.MeasureClass
import FastMultiplication.ShorVerification.Implementation.Reference.ReferenceShorImplementation
import FastMultiplication.ShorVerification.Framework.ToomCookTable
import FastMultiplication.ShorVerification.Submission.Decide
import FastMultiplication.ShorVerification.Submission.Correct
import FastMultiplication.ShorVerification.Submission.Score
