import FastMultiplication.ShorVerification.Implementation.Reference.ReferenceReadiness
import FastMultiplication.ShorVerification.Framework.Instantiation.QSemantics
import FastMultiplication.ShorVerification.Framework.Instantiation.RegEncoding

namespace Shor
namespace Reference

/-!
# Reference LowGate Shor program

This file turns the deterministic reference register allocator into the concrete
LowGate circuit family required by `ShorImplementation`.

The framework exposes only a natural-number precision level `m`.  The reference
implementation translates `m` into its private approximation parameter `η`
(`referencePrecision`, defined in `Reference.ReferencePrecision`), allocates all
implementation-specific storage, proves the resulting layout satisfies the
static circuit requirements, and lowers the resulting approximate
order-finding circuit.

After fixing `lowering`, the public shape is exactly

    ShorOrderFindingInstance → ℕ → LowGate.
-/

/-! =========================================================
    Section 2: Static setup generated by the allocator
========================================================= -/

/--
The minimal approximate-Shor setup generated internally at precision level
`m`.

This is a proof object only; it is not part of the framework-facing interface.
-/
def referenceMinimalSetup
    {qs : QSemantics}
    [RegEncoding qs.Basis]
    (lowering : ShorLoweringSetup)
    (inst : ShorOrderFindingInstance)
    (m : ℕ) :
    let η := referencePrecision m
    let layout := allocateReferenceLayout lowering.ops inst m
    ShorApproxSetupMinimal
      qs
      η
      inst.N
      layout.x
      layout.data
      layout.work
      layout.scratch
      layout.flag
      (RegEncoding.zero (Basis := qs.Basis)) := by
  dsimp

  exact
    allocatedReferenceApproxSetupMinimal
      (qs := qs)
      lowering.ops
      inst
      m

/--
The full approximate-Shor setup reconstructed from the allocator's minimal
facts.
-/
noncomputable def referenceApproxSetup
    {qs : QSemantics}
    [RegEncoding qs.Basis]
    (lowering : ShorLoweringSetup)
    (inst : ShorOrderFindingInstance)
    (m : ℕ) :
    let η := referencePrecision m
    let layout := allocateReferenceLayout lowering.ops inst m
    ShorApproxSetup
      qs
      η
      inst.N
      layout.x
      layout.data
      layout.work
      layout.scratch
      layout.flag
      (RegEncoding.zero (Basis := qs.Basis)) := by
  dsimp

  exact
    ShorApproxSetupMinimal.toShorApproxSetup
      (referenceMinimalSetup
        (qs := qs)
        lowering
        inst
        m)

/--
The complete lowering workspace proof generated internally for the reference
circuit.
-/
def referenceLowerWorkspace
    {qs : QSemantics}
    [RegEncoding qs.Basis]
    (lowering : ShorLoweringSetup)
    (inst : ShorOrderFindingInstance)
    (m : ℕ) :
    let layout := allocateReferenceLayout lowering.ops inst m
    let hsetup :=
      referenceApproxSetup
        (qs := qs)
        lowering
        inst
        m
    GateWorkspaceOK
      lowering.ops
      (orderFindingApprox
        inst.a
        inst.N
        layout.x
        layout.data
        layout.work
        layout.scratch
        layout.flag
        hsetup.circuit_workspace
        hsetup.step4_workspace) := by
  dsimp
  exact
    gateWorkspaceOK_orderFindingApprox
      (ops := lowering.ops)
      (η := referencePrecision m)
      (a := inst.a)
      (N := inst.N)
      (x := (allocateReferenceLayout lowering.ops inst m).x)
      (data := (allocateReferenceLayout lowering.ops inst m).data)
      (work := (allocateReferenceLayout lowering.ops inst m).work)
      (scratch := (allocateReferenceLayout lowering.ops inst m).scratch)
      (flag := (allocateReferenceLayout lowering.ops inst m).flag)
      (b0 := RegEncoding.zero (Basis := qs.Basis))
      (referenceApproxSetup (qs := qs) lowering inst m)
      (allocatedReferenceWorkspaceLargeEnough
        lowering.ops inst m)

/-! =========================================================
    Section 3: Concrete LowGate program
========================================================= -/

/--
Static lowering-workspace witness for the reference circuit, stated without
any `QSemantics` argument.

The underlying fact is proved by instantiating `gateWorkspaceOK_orderFindingApprox`
at an arbitrary concrete quantum semantics (`ConcreteQSemantics.concreteQSemantics`): the
conclusion `GateWorkspaceOK ops (orderFindingApprox ...)` no longer mentions
`qs` once `orderFindingApprox` itself does not, so the choice of witness is
immaterial and does not leak into the statement.
-/
private theorem reference_gateWorkspaceOK_orderFindingApprox
    (lowering : ShorLoweringSetup)
    (inst : ShorOrderFindingInstance)
    (m : ℕ) :
    GateWorkspaceOK lowering.ops
      (orderFindingApprox inst.a inst.N
        (allocateReferenceLayout lowering.ops inst m).x
        (allocateReferenceLayout lowering.ops inst m).data
        (allocateReferenceLayout lowering.ops inst m).work
        (allocateReferenceLayout lowering.ops inst m).scratch
        (allocateReferenceLayout lowering.ops inst m).flag
        (reference_modMulCircuitWorkspaceOK lowering.ops inst m)
        (reference_step4Workspace lowering.ops inst m)) := by
  exact
    gateWorkspaceOK_orderFindingApprox
      (qs := ConcreteQSemantics.concreteQSemantics)
      (ops := lowering.ops)
      (η := referencePrecision m)
      (a := inst.a)
      (N := inst.N)
      (x := (allocateReferenceLayout lowering.ops inst m).x)
      (data := (allocateReferenceLayout lowering.ops inst m).data)
      (work := (allocateReferenceLayout lowering.ops inst m).work)
      (scratch := (allocateReferenceLayout lowering.ops inst m).scratch)
      (flag := (allocateReferenceLayout lowering.ops inst m).flag)
      (b0 := RegEncoding.zero (Basis := ConcreteQSemantics.concreteQSemantics.Basis))
      (referenceApproxSetup (qs := ConcreteQSemantics.concreteQSemantics) lowering inst m)
      (allocatedReferenceWorkspaceLargeEnough lowering.ops inst m)

/--
The concrete reference implementation of approximate Shor order finding.

All implementation-specific choices are internal:

* `m` determines the approximation parameter `η`;
* `allocateReferenceLayout` chooses all physical reserve/workspace qubits;
* the allocator proves the modular-arithmetic workspace requirements; and
* `orderFindingApproxLow` produces the final `LowGate`.

This definition mentions no `QSemantics`: after `lowering` is fixed, the
exposed circuit family has exactly the construction-free shape required by
`ShorImplementation`:

    ShorOrderFindingInstance → ℕ → LowGate.
-/
def referenceShorCircuit
    (lowering : ShorLoweringSetup)
    (inst : ShorOrderFindingInstance)
    (m : ℕ) : LowGate :=
  let layout := allocateReferenceLayout lowering.ops inst m
  orderFindingApproxLow lowering.k lowering.hk lowering.ops
      inst.a inst.N layout.x layout.data layout.work layout.scratch layout.flag
      (reference_modMulCircuitWorkspaceOK lowering.ops inst m)
      (reference_step4Workspace lowering.ops inst m)
      (reference_gateWorkspaceOK_orderFindingApprox lowering inst m)

/-! =========================================================
    Section 4: Framework-facing Shor program
========================================================= -/

/--
The framework-facing reference Shor implementation.

The reference implementation chooses both the circuit and the register whose
measurement contains the order-finding result.
-/
def referenceShorProg
    (lowering : ShorLoweringSetup)
    (inst : ShorOrderFindingInstance)
    (m : ℕ) : ShorOrderFindingProgram :=
  {
    circuit := referenceShorCircuit lowering inst m

    output := (allocateReferenceLayout lowering.ops inst m).x.active
  }
end Reference
end Shor
