import FastMultiplication.ShorVerification.Implementation.Reference.ReferenceReadiness

namespace Shor
namespace Reference

noncomputable section

/-!
# Reference LowGate Shor program

This file turns the deterministic reference register allocator into the concrete
LowGate circuit family required by `ShorImplementation`.

The framework exposes only a natural-number precision level `m`.  The reference
implementation translates `m` into its private approximation parameter `η`,
allocates all implementation-specific storage, proves the resulting layout
satisfies the static circuit requirements, and lowers the resulting approximate
order-finding circuit.

After fixing `lowering`, the public shape is exactly

    ShorOrderFindingInstance → ℕ → LowGate.
-/

/-! =========================================================
    Section 1: Private precision schedule
========================================================= -/

/--
Approximation parameter used by the reference implementation at precision
level `m`.

The offset by `3` ensures that every precision level satisfies

    0 < η < 1 / 2,

including `m = 0`, while `η → 0` as `m → ∞`.
-/
noncomputable def referencePrecision (m : ℕ) : ℝ :=
  1 / ((m : ℝ) + 3)

/-- Every reference precision parameter is positive. -/
theorem referencePrecision_pos (m : ℕ) :
    0 < referencePrecision m := by
  unfold referencePrecision
  positivity

/-- Every reference precision parameter lies below `1 / 2`. -/
theorem referencePrecision_lt_half (m : ℕ) :
    referencePrecision m < (1 / 2 : ℝ) := by
  unfold referencePrecision

  have hden :
      (0 : ℝ) < (m : ℝ) + 3 := by
    positivity

  rw [div_lt_iff₀ hden]

  have hmnonneg : (0 : ℝ) ≤ (m : ℝ) := by
    positivity
  nlinarith

/-! =========================================================
    Section 2: Static setup generated by the allocator
========================================================= -/

/--
The minimal approximate-Shor setup generated internally at precision level
`m`.

This is a proof object only; it is not part of the framework-facing interface.
-/
noncomputable def referenceMinimalSetup
    {qs : QSemantics}
    [RegEncoding qs.Basis]
    (lowering : ShorLoweringSetup)
    (inst : ShorOrderFindingInstance)
    (m : ℕ) :
    let η := referencePrecision m
    let layout := allocateReferenceLayout lowering.ops inst η
    ShorApproxSetupMinimal
      qs
      η
      layout.x
      layout.data
      layout.work
      layout.flag
      (RegEncoding.zero (Basis := qs.Basis)) := by
  dsimp

  exact
    allocatedReferenceApproxSetupMinimal
      (qs := qs)
      lowering.ops
      inst
      (referencePrecision m)
      (referencePrecision_pos m)
      (referencePrecision_lt_half m)

/--
The full approximate-Shor setup reconstructed from the allocator's minimal
facts.
-/
noncomputable def referenceApproxSetup
    {qs : QSemantics}
    [RegEncoding qs.Basis]
    (lowering : ShorLoweringSetup)
    (inst : ShorOrderFindingInstance)
    (m : ℕ) :
    let η := referencePrecision m
    let layout := allocateReferenceLayout lowering.ops inst η
    ShorApproxSetup
      qs
      η
      layout.x
      layout.data
      layout.work
      layout.flag
      (RegEncoding.zero (Basis := qs.Basis)) := by
  dsimp

  exact
    ShorApproxSetupMinimal.toShorApproxSetup
      (referenceMinimalSetup
        (qs := qs)
        lowering
        inst
        m)

/--
The complete lowering workspace proof generated internally for the reference
circuit.
-/
noncomputable def referenceLowerWorkspace
    {qs : QSemantics}
    [RegEncoding qs.Basis]
    (lowering : ShorLoweringSetup)
    (inst : ShorOrderFindingInstance)
    (m : ℕ) :
    let η := referencePrecision m
    let layout := allocateReferenceLayout lowering.ops inst η
    let hsetup :=
      referenceApproxSetup
        (qs := qs)
        lowering
        inst
        m
    GateWorkspaceOK
      lowering.ops
      (orderFindingApprox
        qs
        inst.a
        inst.N
        layout.x
        layout.data
        layout.work
        layout.flag
        hsetup.circuit_workspace) := by
  dsimp

  let η := referencePrecision m
  let layout := allocateReferenceLayout lowering.ops inst η

  have hsetup :
      ShorApproxSetup
        qs
        η
        layout.x
        layout.data
        layout.work
        layout.flag
        (RegEncoding.zero (Basis := qs.Basis)) := by
    simpa [η, layout] using
      referenceApproxSetup
        (qs := qs)
        lowering
        inst
        m

  have hlarge :
      ShorWorkspaceLargeEnough
        lowering.ops
        layout.x
        layout.data
        layout.work := by
    simpa [layout] using
      allocatedReferenceWorkspaceLargeEnough
        lowering.ops
        inst
        η

  exact
    gateWorkspaceOK_orderFindingApprox
      (ops := lowering.ops)
      (η := η)
      (a := inst.a)
      (N := inst.N)
      (x := layout.x)
      (data := layout.data)
      (work := layout.work)
      (flag := layout.flag)
      (b0 := RegEncoding.zero (Basis := qs.Basis))
      hsetup
      hlarge

/-! =========================================================
    Section 3: Concrete LowGate program
========================================================= -/

/--
The concrete reference implementation of approximate Shor order finding.

All implementation-specific choices are internal:

* `m` determines the approximation parameter `η`;
* `allocateReferenceLayout` chooses all physical reserve/workspace qubits;
* the allocator proves the modular-arithmetic workspace requirements;
* `referenceLowerWorkspace` proves the recursive lowering workspace; and
* `orderFindingApproxLow` produces the final `LowGate`.

After `lowering` is fixed, the exposed circuit family has exactly the
construction-free shape required by `ShorImplementation`:

    ShorOrderFindingInstance → ℕ → LowGate.
-/
noncomputable def referenceShorProg
    {qs : QSemantics}
    [RegEncoding qs.Basis]
    (lowering : ShorLoweringSetup)
    (inst : ShorOrderFindingInstance)
    (m : ℕ) : LowGate := by
  let η := referencePrecision m
  let layout := allocateReferenceLayout lowering.ops inst η

  have hsetup :
      ShorApproxSetup
        qs
        η
        layout.x
        layout.data
        layout.work
        layout.flag
        (RegEncoding.zero (Basis := qs.Basis)) := by
    simpa [η, layout] using
      referenceApproxSetup
        (qs := qs)
        lowering
        inst
        m

  have hworkspace :
      GateWorkspaceOK
        lowering.ops
        (orderFindingApprox
          qs
          inst.a
          inst.N
          layout.x
          layout.data
          layout.work
          layout.flag
          hsetup.circuit_workspace) := by
    simpa [η, layout, hsetup] using
      referenceLowerWorkspace
        (qs := qs)
        lowering
        inst
        m

  exact
    orderFindingApproxLow
      qs
      lowering.k
      lowering.hk
      lowering.ops
      inst.a
      inst.N
      layout.x
      layout.data
      layout.work
      layout.flag
      hsetup.circuit_workspace
      hworkspace

end
end Reference
end Shor
